/** @type {Record<string, { zh: string, en: string }>} */
export const UI = {
  aboutTitle: { zh: '关于我', en: 'About' },
  emptyProjects: { zh: '暂无项目', en: 'No projects yet' },
  loadError: { zh: '无法加载作品集数据。', en: 'Could not load portfolio data.' },
  loading: { zh: '加载中', en: 'Loading' },
  loaderKicker: { zh: '实践 × 养成', en: 'Practice × Formation' },
  loaderLoop: { zh: '从 Demo 到交付', en: 'From demo to delivery' },
  loaderWork: { zh: '实践', en: 'Practice' },
  loaderFormation: { zh: '养成', en: 'Formation' },
  loaderHello: { zh: '嗨，我是加义。', en: "Hi — It's Jiayi." },
  loaderHelloName: { zh: '加义', en: 'Jiayi' },
  loaderPairing: { zh: '配对中', en: 'Pairing' },
  loaderReady: { zh: '序列可读', en: 'Sequence readable' },
  loaderHelixAria: {
    zh: '反向平行双螺旋正在从左到右配对',
    en: 'Antiparallel double helix pairing from left to right',
  },
  footerRole: { zh: '产品 & UX 设计师', en: 'Product & UX Designer' },
  langZh: { zh: '中文', en: '中文' },
  langEn: { zh: 'EN', en: 'EN' },
  switchToEn: { zh: 'Switch to English', en: 'Switch to English' },
  switchToZh: { zh: '切换到中文', en: 'Switch to Chinese' },
  themeToggle: { zh: '外观', en: 'Appearance' },
  switchToDark: { zh: '切换到深色模式', en: 'Switch to dark mode' },
  switchToLight: { zh: '切换到浅色模式', en: 'Switch to light mode' },
  heroCarouselLabel: { zh: '作品展示', en: 'Work showcase' },
  heroCarouselPrev: { zh: '上一张', en: 'Previous slide' },
  heroCarouselNext: { zh: '下一张', en: 'Next slide' },
  heroCarouselPause: { zh: '暂停轮播', en: 'Pause carousel' },
  heroCarouselPlay: { zh: '继续轮播', en: 'Resume carousel' },
  sidebarWork: { zh: '工作', en: 'Work' },
  sidebarEducation: { zh: '学历', en: 'Education' },
  sidebarMoreAbout: { zh: '更多关于我', en: 'More about me' },
  sidebarInstagram: { zh: 'Instagram（新窗口打开）', en: 'Instagram (opens in new tab)' },
  sidebarLinkedIn: { zh: 'LinkedIn（新窗口打开）', en: 'LinkedIn (opens in new tab)' },
  sidebarPresent: { zh: '至今', en: 'Present' },
  sidebarYearAxis: { zh: '年份', en: 'Year' },
  helixAria: {
    zh: '工作与学历构成的反向平行双螺旋时间线',
    en: 'Antiparallel double-helix of work and education',
  },
  helixPlay: { zh: 'Play', en: 'Play' },
  helixPause: { zh: 'Pause', en: 'Pause' },
  helixLabelsHide: { zh: 'Hide', en: 'Hide' },
  helixLabelsShow: { zh: 'Show', en: 'Show' },
  blogTitle: { zh: 'Blog', en: 'Blog' },
  blogViewAll: { zh: '全部文章', en: 'All posts' },
  blogBack: { zh: '全部文章', en: 'All posts' },
  blogFilterAria: { zh: '文章筛选', en: 'Filter posts' },
  ctaViewFeatured: { zh: '查看精选案例', en: 'View featured work' },
  ctaViewAll: { zh: '浏览全部作品', en: 'Browse all projects' },
  ctaContact: { zh: '联系我', en: 'Get in touch' },
  footerContact: { zh: '联系', en: 'Contact' },
  footerEmail: { zh: '邮件', en: 'Email' },
  footerPhone: { zh: '电话', en: 'Phone' },
  sidebarEmail: { zh: '邮箱', en: 'Email' },
  sidebarPhone: { zh: '电话', en: 'Phone' },
  footerLinkedIn: { zh: 'LinkedIn', en: 'LinkedIn' },
  footerResume: { zh: '下载简历', en: 'Download résumé' },
  footerInstagram: { zh: 'Instagram', en: 'Instagram' },
  caseStudyRole: { zh: '角色', en: 'Role' },
  caseStudyTimeline: { zh: '周期', en: 'Timeline' },
  caseStudyTeam: { zh: '协作', en: 'Team' },
  caseStudyProblem: { zh: '背景与问题', en: 'Context & problem' },
  caseStudyApproach: { zh: '方法与路径', en: 'Approach' },
  caseStudyImpact: { zh: '成果', en: 'Impact' },
  featuredLabel: { zh: '精选', en: 'Featured' },
  confidentialLabel: { zh: '保密', en: 'Confidential' },
  viewLiveProject: { zh: '查看在线演示', en: 'View live demo' },
  blogReadMore: { zh: '阅读全文', en: 'Read article' },
  blogEmpty: { zh: '暂无文章', en: 'No articles yet' },
  blogClose: { zh: '关闭文章', en: 'Close article' },
  blogPaneLabel: { zh: '文章详情', en: 'Article detail' },
};
