/** @type {Record<string, { zh: string, en: string }>} */
export const UI = {
  aboutTitle: { zh: '关于我', en: 'About' },
  emptyProjects: { zh: '暂无项目', en: 'No projects yet' },
  loadError: { zh: '无法加载作品集数据。', en: 'Could not load portfolio data.' },
  footerRole: { zh: '产品 & UX 设计师', en: 'Product & UX Designer' },
  langZh: { zh: '中文', en: '中文' },
  langEn: { zh: 'EN', en: 'EN' },
  switchToEn: { zh: 'Switch to English', en: 'Switch to English' },
  switchToZh: { zh: '切换到中文', en: 'Switch to Chinese' },
  heroCarouselLabel: { zh: '作品展示', en: 'Work showcase' },
  heroCarouselPrev: { zh: '上一张', en: 'Previous slide' },
  heroCarouselNext: { zh: '下一张', en: 'Next slide' },
  heroCarouselPause: { zh: '暂停轮播', en: 'Pause carousel' },
  heroCarouselPlay: { zh: '继续轮播', en: 'Resume carousel' },
  sidebarWork: { zh: '工作', en: 'Work' },
  sidebarEducation: { zh: '学历', en: 'Education' },
  sidebarMoreAbout: { zh: '更多关于我', en: 'More about me' },
  sidebarInstagram: { zh: 'Instagram（新窗口打开）', en: 'Instagram (opens in new tab)' },
  sidebarPresent: { zh: '至今', en: 'Present' },
  sidebarYearAxis: { zh: '年份', en: 'Year' },
  blogTitle: { zh: '写作', en: 'Writing' },
  ctaViewFeatured: { zh: '查看精选案例', en: 'View featured work' },
  ctaViewAll: { zh: '浏览全部作品', en: 'Browse all projects' },
  ctaContact: { zh: '联系我', en: 'Get in touch' },
  footerContact: { zh: '联系', en: 'Contact' },
  footerEmail: { zh: '邮件', en: 'Email' },
  footerLinkedIn: { zh: 'LinkedIn', en: 'LinkedIn' },
  footerResume: { zh: '下载简历', en: 'Download résumé' },
  footerInstagram: { zh: 'Instagram', en: 'Instagram' },
  caseStudyRole: { zh: '角色', en: 'Role' },
  caseStudyTimeline: { zh: '周期', en: 'Timeline' },
  caseStudyTeam: { zh: '协作', en: 'Team' },
  caseStudyProblem: { zh: '背景与问题', en: 'Context & problem' },
  caseStudyApproach: { zh: '方法与路径', en: 'Approach' },
  caseStudyImpact: { zh: '成果', en: 'Impact' },
  featuredLabel: { zh: '精选', en: 'Featured' },
  confidentialLabel: { zh: '保密', en: 'Confidential' },
  viewLiveProject: { zh: '查看在线演示', en: 'View live demo' },
  blogReadMore: { zh: '阅读全文', en: 'Read article' },
  blogEmpty: { zh: '暂无文章', en: 'No articles yet' },
};
